name: My First workflow
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
           - name: checkout Repo
             uses: actions/checkout@v6 

           - name: Install cowsay program
             run: sudo apt-get install cowsay -y

           - name: Execute cowsay CMD
             run: cowsay -f lion "Run for cover,I am a LION ....ROAR" >> lion.txt   

           - name: Test file exists
             run: grep -i "lion" lion.txt
             
           - name: Read file
             run: cat lion.txt
            
           - name: checkout Repo files
             run: ls -ltra  